import type { ContractJSONValue, DeviceActionContract, JsonSchema } from "./model.js";
import type { GeneratedArtifact, PreparedContractBundle } from "./emitTypeScript.js";

/** Emit Foundation-only Swift wire metadata grouped by provider. */
export function emitSwift(prepared: PreparedContractBundle): GeneratedArtifact[] {
  const providers = [
    {
      provider: "core",
      typeName: "CoreActionContracts",
      path: "Sources/iOSExploreServer/Generated/CoreActionContracts.swift",
      moduleImport: ""
    },
    {
      provider: "uikit",
      typeName: "UIKitActionContracts",
      path: "Sources/iOSExploreUIKit/Generated/UIKitActionContracts.swift",
      moduleImport: "import iOSExploreServer\n"
    },
    {
      provider: "diagnostics",
      typeName: "DiagnosticsActionContracts",
      path: "Sources/iOSExploreDiagnostics/Generated/DiagnosticsActionContracts.swift",
      moduleImport: "import iOSExploreServer\n"
    }
  ] as const;

  return providers.map(configuration => {
    const contracts = prepared.bundle.deviceActions.filter(action => action.provider === configuration.provider);
    return {
      path: configuration.path,
      content: renderProviderFile(configuration.typeName, configuration.moduleImport, contracts, prepared)
    };
  });
}

function renderProviderFile(
  typeName: string,
  moduleImport: string,
  contracts: readonly DeviceActionContract[],
  prepared: PreparedContractBundle
): string {
  const schemaMembers = contracts.flatMap(contract => renderInputSchemaMembers(contract));
  const schemaMap = contracts
    .map(contract => `        ${swiftString(contract.action)}: ${actionIdentifier(contract.action)}InputSchema`)
    .join(",\n");
  const contractMembers = contracts
    .map(contract => renderContractMember(contract))
    .join("\n");
  const contractReferences = contracts
    .map(contract => `        ${actionIdentifier(contract.action)}Contract`)
    .join(",\n");

  return [
    "// Generated from contracts/ by the contract generator.",
    `// Contract hash: ${prepared.hash}`,
    "// Do not edit this file directly.",
    "import Foundation",
    moduleImport.trimEnd(),
    "",
    `/// ${providerLabel(typeName)} provider 的 Foundation-only wire contract 元数据。`,
    `public enum ${typeName} {`,
    "    /// HTTP action 协议版本。",
    `    public static let protocolVersion = ${swiftString(prepared.bundle.protocolVersion)}`,
    "    /// 源合同 bundle 的版本。",
    `    public static let contractVersion = ${swiftString(prepared.bundle.contractVersion)}`,
    "    /// 规范化源合同 bundle 的 SHA-256。",
    `    public static let contractHash = ${swiftString(prepared.hash)}`,
    "    /// 当前 provider 的完整命令合同。",
    "    public static let all: [CommandContract] = [",
    contractReferences,
    "    ]",
    "    /// 按 action 名查询完整命令合同。",
    "    public static let byAction: [String: CommandContract] = Dictionary(uniqueKeysWithValues: all.map { contract in",
    "        (contract.action, contract)",
    "    })",
    "    /// 按 action 名查询 typed 字段 schema。",
    "    public static let inputSchemas: [String: CommandInputSchema] = [",
    schemaMap,
    "    ]",
    contractMembers,
    ...schemaMembers,
    "}",
    ""
  ].filter(line => line.length > 0).join("\n");
}

function renderContractMember(contract: DeviceActionContract): string {
  const identifier = actionIdentifier(contract.action);
  const errors = contract.errors.map(error => swiftString(error)).join(", ");
  return [
    `    static let ${identifier}Contract = CommandContract(`,
    `        action: ${swiftString(contract.action)},`,
    `        description: ${swiftString(contract.description)},`,
    `        inputSchema: ${identifier}InputSchema,`,
    `        provider: .${contract.provider},`,
    `        stability: .${contract.stability},`,
    `        resultKind: .${contract.result.kind},`,
    `        declaredErrors: [${errors}],`,
    `        idempotency: .${contract.idempotency},`,
    `        timeoutClass: .${contract.timeoutClass},`,
    "        contractVersion: contractVersion,",
    "        contractHash: contractHash,",
    "        contractSource: .generated",
    "    )"
  ].join("\n");
}

function renderInputSchemaMembers(contract: DeviceActionContract): string[] {
  const identifier = actionIdentifier(contract.action);
  const schema = contract.inputSchema;
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const fields = Object.keys(properties).sort();
  const fieldMembers: string[] = [];
  const fieldReferences: string[] = [];

  for (const name of fields) {
    const fieldIdentifier = `${identifier}${fieldIdentifierPart(name)}Field`;
    const emission = emitField(name, properties[name]!, required.has(name));
    fieldMembers.push(`    static let ${fieldIdentifier} = ${emission.expression}`);
    fieldReferences.push(emission.typed ? `${fieldIdentifier}.erased` : fieldIdentifier);
  }

  const constraints = swiftConstraints(schema["x-iosExplore-constraints"]);
  const constraintArgument = constraints.length === 0 ? "" : `,\n        constraints: [${constraints.join(", ")}]`;
  const fieldsExpression = fieldReferences.length === 0 ? "[]" : `[${fieldReferences.join(", ")}]`;
  fieldMembers.push(
    `    static let ${identifier}InputSchema = CommandInputSchema(fields: ${fieldsExpression}, additionalProperties: ${schema.additionalProperties === true}${constraintArgument})`
  );
  return fieldMembers;
}

interface SwiftFieldEmission {
  readonly expression: string;
  readonly typed: boolean;
}

function emitField(name: string, schema: JsonSchema, required: boolean): SwiftFieldEmission {
  const description = schema.description ?? "";
  if (isBooleanWithDefault(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.bool(${swiftString(name)}, default: ${schema.default}, description: ${swiftString(description)})`
    };
  }
  if (isRequiredString(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.requiredString(${swiftString(name)}, description: ${swiftString(description)})`
    };
  }
  if (isNullableString(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalString(${swiftString(name)}, description: ${swiftString(description)})`
    };
  }
  if (isRequiredArray(schema, required)) {
    const argumentsList = [
      swiftString(name),
      `description: ${swiftString(description)}`
    ];
    if (schema.items !== undefined) argumentsList.push(`itemsSchema: ${swiftJSONObject(schema.items as unknown as Record<string, ContractJSONValue>)}`);
    if (schema.minItems !== undefined) argumentsList.push(`minimumCount: ${schema.minItems}`);
    if (schema.maxItems !== undefined) argumentsList.push(`maximumCount: ${schema.maxItems}`);
    return { typed: true, expression: `CommandFields.requiredArray(${argumentsList.join(", ")})` };
  }
  if (isNullableFiniteNumber(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalFiniteNumber(${swiftString(name)}, description: ${swiftString(description)})`
    };
  }
  if (isRequiredBoundedInt(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.requiredInt(${swiftString(name)}, range: ${schema.minimum}...${schema.maximum}, description: ${swiftString(description)})`
    };
  }
  if (isDefaultBoundedInt(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.int(${swiftString(name)}, range: ${schema.minimum}...${schema.maximum}, default: ${schema.default}, description: ${swiftString(description)})`
    };
  }
  return {
    typed: false,
    expression: `AnyCommandField(name: ${swiftString(name)}, schema: ${swiftFieldSchema(schema, required)})`
  };
}

function isBooleanWithDefault(schema: JsonSchema, required: boolean): boolean {
  return !required && schema.type === "boolean" && typeof schema.default === "boolean" && hasOnlyKeys(schema, ["type", "description", "default"]);
}

function isRequiredString(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "string" && hasOnlyKeys(schema, ["type", "description"]);
}

function isNullableString(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "string") && hasOnlyKeys(schema, ["type", "description"]);
}

function isRequiredArray(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "array" && schema.uniqueItems === undefined &&
    hasOnlyKeys(schema, ["type", "description", "items", "minItems", "maxItems"]);
}

function isNullableFiniteNumber(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "number") && hasOnlyKeys(schema, ["type", "description"]);
}

function isRequiredBoundedInt(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "integer" && isSafeInteger(schema.minimum) && isSafeInteger(schema.maximum) &&
    hasOnlyKeys(schema, ["type", "description", "minimum", "maximum"]);
}

function isDefaultBoundedInt(schema: JsonSchema, required: boolean): boolean {
  return !required && schema.type === "integer" && isSafeInteger(schema.minimum) && isSafeInteger(schema.maximum) &&
    isSafeInteger(schema.default) && hasOnlyKeys(schema, ["type", "description", "default", "minimum", "maximum"]);
}

function isNullableType(schema: JsonSchema, type: "string" | "number"): boolean {
  return Array.isArray(schema.type) && schema.type.length === 2 && schema.type.includes(type) && schema.type.includes("null");
}

function isSafeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value);
}

function hasOnlyKeys(schema: JsonSchema, keys: readonly string[]): boolean {
  const allowed = new Set(keys);
  return Object.keys(schema).every(key => allowed.has(key));
}

function swiftFieldSchema(schema: JsonSchema, required: boolean): string {
  const types = Array.isArray(schema.type) ? schema.type : schema.type === undefined ? [] : [schema.type];
  const nonNullType = types.find(type => type !== "null") ?? "object";
  const allowsNull = types.includes("null");
  const parameters = [
    `type: .${nonNullType}`,
    `required: ${required}`,
    `description: ${swiftString(schema.description ?? "")}`
  ];
  if (schema.default !== undefined) parameters.push(`defaultValue: ${swiftJSONValue(schema.default)}`);
  if (allowsNull) parameters.push("allowsNull: true");
  if (schema.minimum !== undefined) parameters.push(`minimum: ${schema.minimum}`);
  if (schema.maximum !== undefined) parameters.push(`maximum: ${schema.maximum}`);
  if (schema.enum !== undefined && schema.enum.every(value => typeof value === "string")) {
    parameters.push(`enumValues: [${schema.enum.map(value => swiftString(value as string)).join(", ")}]`);
  }

  const extra = withoutFieldSchemaKeys(schema);
  if (Object.keys(extra).length > 0) parameters.push(`extraSchema: ${swiftJSONObject(extra)}`);
  return `CommandFieldSchema(${parameters.join(", ")})`;
}

function withoutFieldSchemaKeys(schema: JsonSchema): Record<string, ContractJSONValue> {
  const extra: Record<string, ContractJSONValue> = {};
  for (const key of Object.keys(schema).sort()) {
    if (["$ref", "description", "default", "minimum", "maximum"].includes(key)) continue;
    if (key === "type" && isRepresentableFieldType(schema)) continue;
    if (key === "enum" && schema.enum?.every(value => typeof value === "string")) continue;
    const value = schema[key as keyof JsonSchema];
    if (value !== undefined) extra[key] = value as ContractJSONValue;
  }
  return extra;
}

function isRepresentableFieldType(schema: JsonSchema): boolean {
  if (typeof schema.type === "string") return schema.type !== "null";
  return Array.isArray(schema.type) && schema.type.length === 2 && schema.type.includes("null") &&
    schema.type.some(type => type !== "null");
}

function swiftConstraints(value: Record<string, ContractJSONValue> | undefined): string[] {
  if (value === undefined) return [];
  const constraints: string[] = [];
  const exactlyOne = value.exactlyOneOf;
  if (Array.isArray(exactlyOne) && exactlyOne.every(item => typeof item === "string")) {
    constraints.push(`.exactlyOneOf([${exactlyOne.map(item => swiftString(item as string)).join(", ")}])`);
  }
  const mutuallyExclusive = value.mutuallyExclusive;
  if (Array.isArray(mutuallyExclusive) && mutuallyExclusive.every(item => typeof item === "string")) {
    constraints.push(`.extensionMessage(${swiftString(`mutuallyExclusive: ${(mutuallyExclusive as string[]).join(", ")}`)})`);
  }
  if (typeof value.note === "string") constraints.push(`.extensionMessage(${swiftString(value.note)})`);
  return constraints;
}

function swiftJSON(value: ContractJSONValue): string {
  if (value === null) return ".null";
  if (typeof value === "string") return `.string(${swiftString(value)})`;
  if (typeof value === "boolean") return `.bool(${value})`;
  if (typeof value === "number") return `.double(${String(value)})`;
  if (Array.isArray(value)) return `.array([${value.map(item => swiftJSONValue(item)).join(", ")}])`;
  const entries = Object.keys(value).sort().map(key => `${swiftString(key)}: ${swiftJSONValue(value[key]!)}`);
  if (entries.length === 0) return ".object(JSON([:]))";
  return `.object(JSON([${entries.join(", ")}]))`;
}

function swiftJSONObject(value: Record<string, ContractJSONValue>): string {
  const entries = Object.keys(value).sort().map(key => `${swiftString(key)}: ${swiftJSONValue(value[key]!)}`);
  if (entries.length === 0) return "JSON([:])";
  return `JSON([${entries.join(", ")}])`;
}

function swiftJSONValue(value: ContractJSONValue): string {
  return swiftJSON(value);
}

function swiftString(value: string): string {
  let escaped = "";
  for (const character of value) {
    const codePoint = character.codePointAt(0)!;
    switch (character) {
      case "\\": escaped += "\\\\"; break;
      case '"': escaped += '\\"'; break;
      case "\n": escaped += "\\n"; break;
      case "\r": escaped += "\\r"; break;
      case "\t": escaped += "\\t"; break;
      case "\b": escaped += "\\b"; break;
      case "\f": escaped += "\\f"; break;
      default:
        if (codePoint < 0x20) escaped += `\\u{${codePoint.toString(16)}}`;
        else escaped += character;
    }
  }
  return `"${escaped}"`;
}

function actionIdentifier(action: string): string {
  const parts = action.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "action";
  const first = parts[0]!.charAt(0).toLowerCase() + parts[0]!.slice(1);
  return [first, ...parts.slice(1).map(capitalize)].join("");
}

function fieldIdentifierPart(field: string): string {
  const parts = field.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "Field";
  return parts.map(capitalize).join("");
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function providerLabel(typeName: string): string {
  return typeName.replace(/ActionContracts$/, "");
}
