/**
 * Foundation-only Swift 合同元数据与 typed input 定义生成器。
 *
 * 职责：按 provider（core/uikit/diagnostics）拆分输出到三个模块的 Generated 目录，
 * 保证 Core 产物不 import UIKit（硬规则 2 的构建期保证）；每个 action 同时生成三样
 * 东西：命令元数据（CommandContract）、字段声明与 parser 输入定义（CommandInputDefinition）、
 * wire 校验闭包。
 *
 * 类型策略：只对能精确映射的 schema 选择 typed field helper；其余字段回退到
 * `AnyCommandField`，但仍生成完整 wire validation——不因类型无法表达而静默放宽合同。
 */
import type { ContractJSONValue, DeviceActionContract, JsonSchema } from "./model.js";
import type { GeneratedArtifact, PreparedContractBundle } from "./emitTypeScript.js";

/**
 * 按 core/uikit/diagnostics provider 生成三个互不越界的 Swift 文件。
 *
 * @param prepared 已预处理的合同 bundle（含 hash）。
 * @returns 三个 Swift 产物（path + content）。
 *   示例：core → Sources/iOSExploreServer/Generated/CoreActionContracts.swift
 */
export function emitSwift(prepared: PreparedContractBundle): GeneratedArtifact[] {
  const providers = [
    {
      provider: "core",
      typeName: "CoreActionContracts",
      path: "Sources/iOSExploreServer/Generated/CoreActionContracts.swift",
      moduleImport: ""
    },
    {
      provider: "uikit",
      typeName: "UIKitActionContracts",
      path: "Sources/iOSExploreUIKit/Generated/UIKitActionContracts.swift",
      moduleImport: "import iOSExploreServer\n"
    },
    {
      provider: "diagnostics",
      typeName: "DiagnosticsActionContracts",
      path: "Sources/iOSExploreDiagnostics/Generated/DiagnosticsActionContracts.swift",
      moduleImport: "import iOSExploreServer\n"
    }
  ] as const;

  return providers.map(configuration => {
    const contracts = prepared.bundle.deviceActions.filter(action => action.provider === configuration.provider);
    return {
      path: configuration.path,
      content: renderProviderFile(configuration.typeName, configuration.moduleImport, contracts, prepared)
    };
  });
}

/**
 * 组装单个 provider 文件（一个 enum，含 all/byAction/inputs 三份索引与全部成员）。
 *
 * `all`（合同数组）、`byAction`（按名查询）、`inputs`（执行端 parser）共享同一
 * action 集合——注册、自省与解析不会各自漂移。
 *
 * @param typeName 生成的 Swift 类型名（如 "CoreActionContracts"）。
 * @param moduleImport 顶部 import 行（uikit/diagnostics 需要 import iOSExploreServer）。
 * @param contracts 属于该 provider 的 action 列表。
 * @param prepared 已预处理的 bundle（取 hash 与版本）。
 * @returns Swift 文件内容。
 */
function renderProviderFile(
  typeName: string,
  moduleImport: string,
  contracts: readonly DeviceActionContract[],
  prepared: PreparedContractBundle
): string {
  const inputMembers = contracts.flatMap(contract => renderInputMembers(contract));
  const inputMap = contracts
    .map(contract => `        ${swiftString(contract.action)}: ${actionIdentifier(contract.action)}Input`)
    .join(",\n");
  const contractMembers = contracts
    .map(contract => renderContractMember(contract))
    .join("\n");
  const contractReferences = contracts
    .map(contract => `        ${actionIdentifier(contract.action)}Contract`)
    .join(",\n");

  return [
    "// Generated from contracts/ by the contract generator.",
    `// Contract hash: ${prepared.hash}`,
    "// Do not edit this file directly.",
    "import Foundation",
    moduleImport.trimEnd(),
    "",
    `/// ${providerLabel(typeName)} provider 的 Foundation-only wire contract 元数据。`,
    `public enum ${typeName} {`,
    "    /// HTTP action 协议版本。",
    `    public static let protocolVersion = ${swiftString(prepared.bundle.protocolVersion)}`,
    "    /// 源合同 bundle 的版本。",
    `    public static let contractVersion = ${swiftString(prepared.bundle.contractVersion)}`,
    "    /// 规范化源合同 bundle 的 SHA-256。",
    `    public static let contractHash = ${swiftString(prepared.hash)}`,
    "    /// 当前 provider 的完整命令合同。",
    "    public static let all: [CommandContract] = [",
    contractReferences,
    "    ]",
    "    /// 按 action 名查询完整命令合同。",
    "    public static let byAction: [String: CommandContract] = Dictionary(uniqueKeysWithValues: all.map { contract in",
    "        (contract.action, contract)",
    "    })",
    "    /// 按 action 名查询 Swift 执行端输入定义。",
    "    public static let inputs: [String: CommandInputDefinition] = [",
    inputMap,
    "    ]",
    contractMembers,
    ...inputMembers,
    "}",
    ""
  ].filter(line => line.length > 0).join("\n");
}

/**
 * 把单个 action 的元数据渲染为 `CommandContract` 成员。
 * 只含 Foundation 元数据，不包含 UIKit 类型或 handler 实现。
 *
 * @param contract 设备 action 合同。
 * @returns Swift 成员声明文本。
 */
function renderContractMember(contract: DeviceActionContract): string {
  const identifier = actionIdentifier(contract.action);
  const errors = contract.errors.map(error => swiftString(error)).join(", ");
  return [
    `    static let ${identifier}Contract = CommandContract(`,
    `        action: ${swiftString(contract.action)},`,
    `        description: ${swiftString(contract.description)},`,
    `        provider: .${contract.provider},`,
    `        stability: .${contract.stability},`,
    `        resultKind: .${contract.result.kind},`,
    `        declaredErrors: [${errors}],`,
    `        idempotency: .${contract.idempotency},`,
    `        timeoutClass: .${contract.timeoutClass},`,
    "        contractVersion: contractVersion,",
    "        contractHash: contractHash,",
    "        contractSource: .generated",
    "    )"
  ].join("\n");
}

/**
 * 为一个 action 生成字段声明与 `CommandInputDefinition`（含 wire 校验闭包）。
 *
 * 注意：JSON properties 的**插入顺序**就是合同声明顺序，会影响 parser 读取顺序
 * 测试与字段布局——这里不能重新排序（MCP 工具元数据由 canonical TypeScript 产物负责）。
 *
 * @param contract 设备 action 合同。
 * @returns Swift 成员声明文本行列表。
 */
function renderInputMembers(contract: DeviceActionContract): string[] {
  const identifier = actionIdentifier(contract.action);
  const schema = contract.inputSchema;
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  // JSON 对象插入顺序就是合同声明顺序。保留它以稳定字段布局和 parser 读取顺序测试；
  // MCP 工具元数据由 canonical TypeScript 产物负责。
  const fields = Object.keys(properties);
  const fieldMembers: string[] = [];
  const fieldReferences: string[] = [];

  for (const name of fields) {
    const fieldIdentifier = `${identifier}${fieldIdentifierPart(name)}Field`;
    const itemMembers = renderObjectArrayItemMembers(
      identifier,
      name,
      properties[name]!,
      required.has(name)
    );
    fieldMembers.push(...itemMembers.members);
    const emission = emitField(name, properties[name]!, required.has(name));
    fieldMembers.push(`    static let ${fieldIdentifier} = ${emission.expression}`);
    fieldReferences.push(emission.typed ? `${fieldIdentifier}.erased` : fieldIdentifier);
  }

  const fieldsExpression = fieldReferences.length === 0 ? "[]" : `[${fieldReferences.join(", ")}]`;
  const validationLines = renderObjectValidation(schema, "data", "", "            ");
  fieldMembers.push(
    `    static let ${identifier}Input = CommandInputDefinition(`,
    `        fields: ${fieldsExpression},`,
    `        additionalProperties: ${schema.additionalProperties === true},`,
    "        validate: { data in",
    ...validationLines,
    "        }",
    "    )"
  );
  return fieldMembers;
}

interface ObjectArrayItemEmission {
  /** 插入 provider enum 的 Swift 静态成员源码行。 */
  readonly members: string[];
}

/**
 * 为可由 typed parser 逐项读取的 object-array item 生成独立字段与输入定义。
 *
 * 顶层数组字段仍由 `emitField` 从 canonical `items` 发射；这里的额外声明只为
 * Foundation-only parser 提供稳定的 `CommandField` 引用，避免 parser 再次手写字段规则。
 */
function renderObjectArrayItemMembers(
  actionIdentifierValue: string,
  fieldName: string,
  schema: JsonSchema,
  isRequiredField: boolean
): ObjectArrayItemEmission {
  const item = schema.items;
  if (!isRequiredArray(schema, isRequiredField) || !isObjectArrayItemSchema(schema, item)) {
    return { members: [] };
  }

  const itemIdentifier = `${actionIdentifierValue}${fieldIdentifierPart(fieldName)}Item`;
  const properties = item.properties ?? {};
  const required = new Set(item.required ?? []);
  const fieldMembers: string[] = [];
  const fieldReferences: string[] = [];

  for (const name of Object.keys(properties)) {
    const fieldIdentifier = `${itemIdentifier}${fieldIdentifierPart(name)}Field`;
    const emission = emitField(name, properties[name]!, required.has(name));
    fieldMembers.push(`    static let ${fieldIdentifier} = ${emission.expression}`);
    fieldReferences.push(emission.typed ? `${fieldIdentifier}.erased` : fieldIdentifier);
  }

  const fieldsExpression = fieldReferences.length === 0 ? "[]" : `[${fieldReferences.join(", ")}]`;
  const validationLines = renderObjectValidation(item, "data", "", "            ");
  fieldMembers.push(
    `    static let ${itemIdentifier}Input = CommandInputDefinition(`,
    `        fields: ${fieldsExpression},`,
    `        additionalProperties: ${item.additionalProperties === true},`,
    "        validate: { data in",
    ...validationLines,
    "        }",
    "    )"
  );

  return { members: fieldMembers };
}

function isObjectArrayItemSchema(schema: JsonSchema, item: JsonSchema | undefined): item is JsonSchema & {
  type: "object";
  properties: Record<string, JsonSchema>;
} {
  const isArray = schema.type === "array" || (Array.isArray(schema.type) && schema.type.includes("array"));
  return isArray && item?.type === "object" && item.properties !== undefined;
}

/** 在一次 action validation 中分配不重复的 Swift 临时变量名。 */
interface ValidationRenderContext {
  nextVariable: number;
}

/** 把 canonical object schema 编译为直接的 Swift `CommandWireValidation` 调用。 */
function renderObjectValidation(
  schema: JsonSchema,
  objectExpression: string,
  path: string,
  indent: string
): string[] {
  const context: ValidationRenderContext = { nextVariable: 0 };
  return renderObjectProperties(schema, objectExpression, path, indent, context);
}

/** 按合同声明顺序递归渲染 object properties 的校验代码。 */
function renderObjectProperties(
  schema: JsonSchema,
  objectExpression: string,
  path: string,
  indent: string,
  context: ValidationRenderContext
): string[] {
  assertRuntimeSchemaSupported(schema, path.length === 0 ? "data" : path);
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  return Object.keys(properties).flatMap(name => renderValueValidation(
    properties[name]!,
    `${objectExpression}[${swiftString(name)}]`,
    path.length === 0 ? name : `${path}.${name}`,
    required.has(name),
    true,
    indent,
    context
  ));
}

/**
 * 渲染单个值及其嵌套 object/array 的校验。
 * context 分配的变量名让多层容器生成合法 Swift，同时 optionalExpression 决定 pattern
 * matching 是否需要 `?`，不会把缺失可选字段误判成类型错误。
 */
function renderValueValidation(
  schema: JsonSchema,
  rawExpression: string,
  path: string,
  required: boolean,
  optionalExpression: boolean,
  indent: string,
  context: ValidationRenderContext
): string[] {
  assertRuntimeSchemaSupported(schema, path);
  const types = schemaTypes(schema);
  const argumentsList = [
    rawExpression,
    `path: ${swiftString(path)}`,
    `required: ${required}`,
    `types: [${types.map(type => `.${type}`).join(", ")}]`
  ];
  if (schema.enum !== undefined) {
    argumentsList.push(`enumValues: [${schema.enum.map(swiftJSONValue).join(", ")}]`);
  }
  if (schema.minimum !== undefined) argumentsList.push(`minimum: ${schema.minimum}`);
  if (schema.maximum !== undefined) argumentsList.push(`maximum: ${schema.maximum}`);
  if (schema.exclusiveMinimum !== undefined) argumentsList.push(`exclusiveMinimum: ${schema.exclusiveMinimum}`);
  if (schema.exclusiveMaximum !== undefined) argumentsList.push(`exclusiveMaximum: ${schema.exclusiveMaximum}`);
  if (schema.minItems !== undefined) argumentsList.push(`minimumItems: ${schema.minItems}`);
  if (schema.maxItems !== undefined) argumentsList.push(`maximumItems: ${schema.maxItems}`);
  if (schema.uniqueItems === true) argumentsList.push("uniqueItems: true");

  const lines = [`${indent}try CommandWireValidation.value(${argumentsList.join(", ")})`];
  if (types.includes("object") && schema.properties !== undefined) {
    const variable = `object${context.nextVariable++}`;
    const patternSuffix = optionalExpression ? "?" : "";
    lines.push(`${indent}if case .object(let ${variable})${patternSuffix} = ${rawExpression} {`);
    const allowed = Object.keys(schema.properties).map(swiftString).join(", ");
    lines.push(
      `${indent}    try CommandWireValidation.object(${variable}, path: ${swiftString(path)}, allowedFields: Set([${allowed}]), additionalProperties: ${schema.additionalProperties === true})`
    );
    lines.push(...renderObjectProperties(schema, variable, path, `${indent}    `, context));
    lines.push(`${indent}}`);
  }
  if (types.includes("array") && schema.items !== undefined) {
    const arrayVariable = `array${context.nextVariable++}`;
    const itemVariable = `item${context.nextVariable++}`;
    const patternSuffix = optionalExpression ? "?" : "";
    lines.push(`${indent}if case .array(let ${arrayVariable})${patternSuffix} = ${rawExpression} {`);
    lines.push(`${indent}    for ${itemVariable} in ${arrayVariable} {`);
    lines.push(...renderValueValidation(
      schema.items,
      itemVariable,
      `${path}[]`,
      true,
      false,
      `${indent}        `,
      context
    ));
    lines.push(`${indent}    }`);
    lines.push(`${indent}}`);
  }
  return lines;
}

function schemaTypes(schema: JsonSchema): string[] {
  const types = Array.isArray(schema.type) ? schema.type : schema.type === undefined ? [] : [schema.type];
  if (types.length === 0) throw new Error("device action runtime schema requires an explicit type");
  return types;
}

/**
 * 拒绝 Swift wire validator 尚不能等价表达的 schema。
 * 与其生成看似可用但实际放宽校验的代码，构建应在具体字段路径上直接失败。
 */
function assertRuntimeSchemaSupported(schema: JsonSchema, path: string): void {
  if (schema.oneOf !== undefined || schema.allOf !== undefined || schema.not !== undefined) {
    throw new Error(`device action runtime schema uses an unsupported composite at ${path}`);
  }
  if (typeof schema.additionalProperties === "object") {
    throw new Error(`device action runtime schema uses an unsupported additionalProperties schema at ${path}`);
  }
}

interface SwiftFieldEmission {
  /** 可插入 Swift 静态成员右侧的表达式。 */
  readonly expression: string;
  /** true 表示结果需通过 `.erased` 放入异构字段集合。 */
  readonly typed: boolean;
}

/**
 * 为 schema 选择语义完全匹配的 typed `CommandFields` helper。
 * 下方 shape predicate 不做近似匹配：只有 required/default/nullable/bounds/enum 和 keyword
 * 集合都能由 helper 完整表达时才返回 typed，否则使用 AnyCommandField 并依赖 wire 校验。
 */
function emitField(name: string, schema: JsonSchema, required: boolean): SwiftFieldEmission {
  if (isBooleanWithDefault(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.bool(${swiftString(name)}, default: ${schema.default})`
    };
  }
  if (isRequiredStringEnum(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.requiredStringEnum(${swiftString(name)}, values: ${swiftStringArray(stringEnumValues(schema))})`
    };
  }
  if (isDefaultStringEnum(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.stringEnum(${swiftString(name)}, values: ${swiftStringArray(stringEnumValues(schema))}, default: ${swiftString(schema.default as string)})`
    };
  }
  if (isNullableStringEnum(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalStringEnum(${swiftString(name)}, values: ${swiftStringArray(stringEnumValues(schema))})`
    };
  }
  if (isRequiredString(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.requiredString(${swiftString(name)})`
    };
  }
  if (isNullableString(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalString(${swiftString(name)})`
    };
  }
  if (isRequiredArray(schema, required)) {
    const argumentsList = [
      swiftString(name)
    ];
    if (schema.minItems !== undefined) argumentsList.push(`minimumCount: ${schema.minItems}`);
    if (schema.maxItems !== undefined) argumentsList.push(`maximumCount: ${schema.maxItems}`);
    return { typed: true, expression: `CommandFields.requiredArray(${argumentsList.join(", ")})` };
  }
  if (isNullableStringEnumArray(schema, required)) {
    const items = schema.items!;
    const argumentsList = [
      swiftString(name),
      `values: ${swiftStringArray(stringEnumValues(items))}`
    ];
    return {
      typed: true,
      expression: `CommandFields.optionalStringEnumArray(${argumentsList.join(", ")})`
    };
  }
  if (isNullableBoundedInt(schema, required)) {
    const argumentsList = [swiftString(name)];
    if (schema.minimum !== undefined) argumentsList.push(`minimum: ${schema.minimum}`);
    if (schema.maximum !== undefined) argumentsList.push(`maximum: ${schema.maximum}`);
    return {
      typed: true,
      expression: `CommandFields.optionalInt(${argumentsList.join(", ")})`
    };
  }
  if (isDefaultBoundedFiniteNumber(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.finiteNumber(${finiteNumberArguments(name, schema, true)})`
    };
  }
  if (isNullableBoundedFiniteNumber(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalFiniteNumber(${finiteNumberArguments(name, schema, false)})`
    };
  }
  if (isNullableFiniteNumber(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.optionalFiniteNumber(${swiftString(name)})`
    };
  }
  if (isRequiredBoundedInt(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.requiredInt(${swiftString(name)}, range: ${schema.minimum}...${schema.maximum})`
    };
  }
  if (isDefaultBoundedInt(schema, required)) {
    return {
      typed: true,
      expression: `CommandFields.int(${swiftString(name)}, range: ${schema.minimum}...${schema.maximum}, default: ${schema.default})`
    };
  }
  return {
    typed: false,
    expression: `AnyCommandField(name: ${swiftString(name)})`
  };
}

// 以下 predicate 共同定义 typed field helper 能无损覆盖的 schema 形状。
function isBooleanWithDefault(schema: JsonSchema, required: boolean): boolean {
  return !required && schema.type === "boolean" && typeof schema.default === "boolean" && hasOnlyKeys(schema, ["type", "description", "default"]);
}

function isRequiredStringEnum(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "string" && hasStringEnum(schema, false) &&
    hasOnlyKeys(schema, ["type", "description", "enum"]);
}

function isDefaultStringEnum(schema: JsonSchema, required: boolean): boolean {
  return !required && schema.type === "string" && typeof schema.default === "string" &&
    hasStringEnum(schema, false) && stringEnumValues(schema).includes(schema.default) &&
    hasOnlyKeys(schema, ["type", "description", "enum", "default"]);
}

function isNullableStringEnum(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "string") && hasStringEnum(schema, true) &&
    hasOnlyKeys(schema, ["type", "description", "enum"]);
}

function isRequiredString(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "string" && hasOnlyKeys(schema, ["type", "description"]);
}

function isNullableString(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "string") && hasOnlyKeys(schema, ["type", "description"]);
}

function isRequiredArray(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "array" && schema.uniqueItems === undefined &&
    hasOnlyKeys(schema, ["type", "description", "items", "minItems", "maxItems"]);
}

function isNullableStringEnumArray(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "array") && schema.items !== undefined &&
    schema.items.type === "string" && hasStringEnum(schema.items, false) &&
    hasOnlyKeys(schema, ["type", "description", "items"]) &&
    hasOnlyKeys(schema.items, ["type", "description", "enum"]);
}

function isNullableBoundedInt(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "integer") && hasSafeIntegerBound(schema) &&
    hasOnlyKeys(schema, ["type", "description", "minimum", "maximum"]);
}

function isDefaultBoundedFiniteNumber(schema: JsonSchema, required: boolean): boolean {
  return isNullableBoundedNumberShape(schema, required) && typeof schema.default === "number" &&
    Number.isFinite(schema.default) && hasOnlyKeys(schema, numericFieldKeys(true));
}

function isNullableBoundedFiniteNumber(schema: JsonSchema, required: boolean): boolean {
  return isNullableBoundedNumberShape(schema, required) && schema.default === undefined &&
    hasOnlyKeys(schema, numericFieldKeys(false));
}

function isNullableFiniteNumber(schema: JsonSchema, required: boolean): boolean {
  return !required && isNullableType(schema, "number") && hasOnlyKeys(schema, ["type", "description"]);
}

function isRequiredBoundedInt(schema: JsonSchema, required: boolean): boolean {
  return required && schema.type === "integer" && isSafeInteger(schema.minimum) && isSafeInteger(schema.maximum) &&
    hasOnlyKeys(schema, ["type", "description", "minimum", "maximum"]);
}

function isDefaultBoundedInt(schema: JsonSchema, required: boolean): boolean {
  return !required && schema.type === "integer" && isSafeInteger(schema.minimum) && isSafeInteger(schema.maximum) &&
    isSafeInteger(schema.default) && hasOnlyKeys(schema, ["type", "description", "default", "minimum", "maximum"]);
}

function isNullableType(schema: JsonSchema, type: "string" | "number" | "integer" | "array"): boolean {
  return Array.isArray(schema.type) && schema.type.length === 2 && schema.type.includes(type) && schema.type.includes("null");
}

function hasStringEnum(schema: JsonSchema, nullable: boolean): boolean {
  if (schema.enum === undefined || schema.enum.length === 0) return false;
  if (!schema.enum.every(value => typeof value === "string" || (nullable && value === null))) return false;
  if (nullable && !schema.enum.includes(null)) return false;
  return schema.enum.some(value => typeof value === "string");
}

function stringEnumValues(schema: JsonSchema): string[] {
  return (schema.enum ?? []).filter((value): value is string => typeof value === "string");
}

function hasSafeIntegerBound(schema: JsonSchema): boolean {
  const bounds = [schema.minimum, schema.maximum].filter(value => value !== undefined);
  return bounds.length > 0 && bounds.every(isSafeInteger);
}

function isNullableBoundedNumberShape(schema: JsonSchema, required: boolean): boolean {
  if (required || !isNullableType(schema, "number") || !hasFiniteNumberBound(schema)) return false;
  if (schema.minimum !== undefined && schema.exclusiveMinimum !== undefined) return false;
  if (schema.maximum !== undefined && schema.exclusiveMaximum !== undefined) return false;
  return true;
}

function hasFiniteNumberBound(schema: JsonSchema): boolean {
  const bounds = [schema.minimum, schema.maximum, schema.exclusiveMinimum, schema.exclusiveMaximum]
    .filter(value => value !== undefined);
  return bounds.length > 0 && bounds.every(value => typeof value === "number" && Number.isFinite(value));
}

function numericFieldKeys(hasDefault: boolean): string[] {
  return [
    "type",
    "description",
    ...(hasDefault ? ["default"] : []),
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum"
  ];
}

/** 按 inclusive/exclusive bounds 生成 Swift helper 参数，并显式保留排他性标志。 */
function finiteNumberArguments(name: string, schema: JsonSchema, hasDefault: boolean): string {
  const argumentsList = [swiftString(name)];
  if (hasDefault) argumentsList.push(`default: ${schema.default}`);
  if (schema.exclusiveMinimum !== undefined) {
    argumentsList.push(`minimum: ${schema.exclusiveMinimum}`);
  } else if (schema.minimum !== undefined) {
    argumentsList.push(`minimum: ${schema.minimum}`);
  }
  if (schema.exclusiveMaximum !== undefined) {
    argumentsList.push(`maximum: ${schema.exclusiveMaximum}`);
  } else if (schema.maximum !== undefined) {
    argumentsList.push(`maximum: ${schema.maximum}`);
  }
  if (schema.exclusiveMinimum !== undefined) argumentsList.push("exclusiveMinimum: true");
  if (schema.exclusiveMaximum !== undefined) argumentsList.push("exclusiveMaximum: true");
  return argumentsList.join(", ");
}

function swiftStringArray(values: readonly string[]): string {
  return `[${values.map(swiftString).join(", ")}]`;
}

function isSafeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value);
}

function hasOnlyKeys(schema: JsonSchema, keys: readonly string[]): boolean {
  const allowed = new Set(keys);
  return Object.keys(schema).every(key => allowed.has(key));
}

/** 把合同 JSON 值递归转义为 Swift `JSONValue` 构造表达式。 */
function swiftJSON(value: ContractJSONValue): string {
  if (value === null) return ".null";
  if (typeof value === "string") return `.string(${swiftString(value)})`;
  if (typeof value === "boolean") return `.bool(${value})`;
  if (typeof value === "number") return `.double(${String(value)})`;
  if (Array.isArray(value)) return `.array([${value.map(item => swiftJSONValue(item)).join(", ")}])`;
  const entries = Object.keys(value).sort().map(key => `${swiftString(key)}: ${swiftJSONValue(value[key]!)}`);
  if (entries.length === 0) return ".object(JSON([:]))";
  return `.object(JSON([${entries.join(", ")}]))`;
}

function swiftJSONValue(value: ContractJSONValue): string {
  return swiftJSON(value);
}

/**
 * 生成 Swift 字符串字面量。
 * 显式处理控制字符而非依赖 JSON.stringify，因为 Swift 与 JSON 的转义语法并不完全相同。
 */
function swiftString(value: string): string {
  let escaped = "";
  for (const character of value) {
    const codePoint = character.codePointAt(0)!;
    switch (character) {
      case "\\": escaped += "\\\\"; break;
      case '"': escaped += '\\"'; break;
      case "\n": escaped += "\\n"; break;
      case "\r": escaped += "\\r"; break;
      case "\t": escaped += "\\t"; break;
      case "\b": escaped += "\\b"; break;
      case "\f": escaped += "\\f"; break;
      default:
        if (codePoint < 0x20) escaped += `\\u{${codePoint.toString(16)}}`;
        else escaped += character;
    }
  }
  return `"${escaped}"`;
}

/** 把点号/连字符 action 转为稳定 lowerCamelCase Swift 成员名。 */
function actionIdentifier(action: string): string {
  const parts = action.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "action";
  const first = parts[0]!.charAt(0).toLowerCase() + parts[0]!.slice(1);
  return [first, ...parts.slice(1).map(capitalize)].join("");
}

function fieldIdentifierPart(field: string): string {
  const parts = field.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "Field";
  return parts.map(capitalize).join("");
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function providerLabel(typeName: string): string {
  return typeName.replace(/ActionContracts$/, "");
}
