schemaVersion: 1
enabledWorkflows:
  - simulator
  - device
  - debugging
  - ui-automation
sessionDefaults:
  projectPath: ./Examples/SPMExample/SPMExample.xcodeproj
  scheme: SPMExample
  configuration: Debug
  simulatorName: iPhone 17
  simulatorPlatform: iOS Simulator
  bundleId: com.coo.SPMExample
sessionDefaultsProfiles:
  sim-app:
    projectPath: ./Examples/SPMExample/SPMExample.xcodeproj
    scheme: SPMExample
    configuration: Debug
    simulatorName: iPhone 17
    simulatorPlatform: iOS Simulator
    bundleId: com.coo.SPMExample
  sim-fw:
    projectPath: ./iOSExploreServer/iOSExploreServer.xcodeproj
    scheme: iOSExploreServer
    configuration: Debug
    simulatorName: iPhone 17
    simulatorPlatform: iOS Simulator
  device-app:
    projectPath: ./Examples/SPMExample/SPMExample.xcodeproj
    scheme: SPMExample
    configuration: Debug
    deviceId: 3AC0C7D6-22F6-572B-8368-4047A14BAB52
    platform: iOS
    bundleId: com.coo.SPMExample
